name: Release Pro
on:
  pull_request:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "NIGHTLY_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install
      - name: Release
        uses: borales/actions-yarn@master
        with:
          cmd: build:pr-ca
      - name: Zip&Upload
        uses: actions/upload-artifact@v2
        with:
          name: dashboard-pr-ca-${{ env.NIGHTLY_DATE }}
          path: dist/
          retention-days: 1
